sudo: false
language: c
dist: trusty

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - ulimit -n 4096
  # riak
  - travis_retry curl -s https://packagecloud.io/install/repositories/basho/riak-ts/script.deb.sh | sudo bash
  - apt-get install riak-ts=1.5.2-1
  - sed -r --in-place -e 's/^(search) = .*/\1 = on/' /etc/riak/riak.conf
  - riak start
  - riak ping

matrix:
  include:
#    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.2.1
#      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
#    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.1.3
#      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
#    - env: GHCVER=7.8.4 ARGS="--stack-yaml=.stack-7.8.4.yaml" RIAK=2.0.6
#      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}

#    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.2.1
#      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
#    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.1.3
#      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}
#    - env: GHCVER=7.10.3 ARGS="--stack-yaml=.stack-7.10.3.yaml" RIAK=2.0.6
#      addons: {apt: {packages: [ghc-7.10.3],sources: [hvr-ghc]}}

#    - env: GHCVER=8.0.1 ARGS="" RIAK=2.1.3
#      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}
#    - env: GHCVER=8.0.1 ARGS="" RIAK=2.0.6
#      addons: {apt: {packages: [ghc-8.0.1],sources: [hvr-ghc]}}

    - env: GHCVER=8.0.2 ARGS="--stack-yaml=.stack-8.0.2.yaml" RIAK=1.5.2-1
      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}
#    - env: GHCVER=8.0.2 ARGS="--stack-yaml=.stack-8.0.2.yaml" RIAK=2.1.3
#      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}
#    - env: GHCVER=8.0.2 ARGS="--stack-yaml=.stack-8.0.2.yaml" RIAK=2.0.6
#      addons: {apt: {packages: [ghc-8.0.2],sources: [hvr-ghc]}}

#    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
#      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}
#    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6
#      addons: {apt: {packages: [cabal-install-head,ghc-head], sources: [hvr-ghc]}}

#  allow_failures:
#    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.1.3
#    - env: GHCVER=head ARGS="--resolver=nightly" RIAK=2.0.6

install:
  - stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
  - stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
